model:
  base_learning_rate: 5.0e-06
  # base_learning_rate: 2.5e-06 # swap to this 100k in ?
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    embed_dim: 4
    monitor: &monitor val/rec_loss
    # ckpt_path: "models/sd-v1.4-kl.ckpt"
    # ckpt_path: "models/danbooru-kl-f8.ckpt" # https://mystic.the-eye.eu/public/AI/models/
    # ckpt_path: "models/first_stage_models/kl-f8/model.ckpt" # https://ommer-lab.com/files/latent-diffusion/
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: &image_size 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 500
        kl_weight: 0.000001
        disc_weight: 0.5
lightning:
  trainer:
    precision: 32
    limit_val_batches: 10
    val_check_interval: 500
  callbacks:
    image_logger:
      target: lun.callbacks.ImageLogger
      params:
        batch_frequency: 100
        max_images: 4
    monitored_checkpoint:
      params:
        monitor: *monitor
